controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_api:
    path: /api/{id}
    controller: App\Controller\ApiController::getEventData

